# Generated by Django 5.2.8 on 2025-11-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('bedrooms', models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('Single Room', 'Single Room'), ('One bedroom', 'One bedroom'), ('Two bedroom', 'Two bedroom'), ('Three bedroom', 'Three bedroom'), ('Four bedroom', 'Four bedroom'), ('Five bedroom', 'Five bedroom'), ('Six bedroom', 'Six bedroom')], max_length=20)),
                ('owner_name', models.CharField(max_length=60)),
                ('owner_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property')),
            ],
        ),
    ]
